menu:
    Blog: /
    Archive: /archives/
    FB: https://www.facebook.com/canopus.t
    # Weibo: http://weibo.com/sunchongsheng
    # GitHub: https://github.com/pinggod
    # Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: tds-note
duoshuo:

# Analytics
# google-analytics:
ga: UA-155266193-1

# Copyright Infomation
startyear: 2019
